### ISSUE TITLE
Wist Linting issues in the Adobe Roku SDK

### ISSUE THREAD

**Issue by vbasky** [Adobe-Marketing-Cloud/media-sdks#39]
I see close to 230 issues in the Roku SDK on linting based on Wist rules some of the screenshots attached as below.

<img width="871" alt="screen shot 2019-03-07 at 3 49 34 pm" src="https://user-images.githubusercontent.com/287302/53933132-0368b300-40f1-11e9-936a-f3e781283809.png">
<img width="548" alt="screen shot 2019-03-07 at 3 49 52 pm" src="https://user-images.githubusercontent.com/287302/53933136-0794d080-40f1-11e9-8d93-fc35de246d87.png">
<img width="799" alt="screen shot 2019-03-07 at 3 50 07 pm" src="https://user-images.githubusercontent.com/287302/53933143-0ebbde80-40f1-11e9-997c-4355e3178560.png">
<img width="798" alt="screen shot 2019-03-07 at 3 50 28 pm" src="https://user-images.githubusercontent.com/287302/53933150-17acb000-40f1-11e9-91af-74f9495cb8cc.png">

It would be good to have a wist compliant version of your library or propose a solution otherwise

Wist rules set in the `.wisrtc.json` is as below 

```{
  "rules": {
    "camel-case-func": [
      "error"
    ],    
    "function-return-type": [
      "error"
    ],
    "invalid-associative-array-keys": [
      "error"
    ],
    "no-stop": [
      "error"
    ],
    "no-shorthand-print": [
      "error"
    ],
    "no-print": [
      "off"
    ],
    "no-private-func": [
      "error"
    ],
    "no-void-func": [
      "error"
    ],
    "function-return-statement": [
      "error"
    ]
  },
  "retired": {
    "comma-separated-arrays": [
      "error"
    ],
    "no-comma-separated-arrays": [
      "error"
    ]    
  }
}
```

Referencing https://github.com/Adobe-Marketing-Cloud/media-sdks/issues/38 which was closed, the .wisrtc.json is set at the project root level, giving issues in the Atom or VSCode editors. I have modified by build script to ignore the SDK libraries at build but that doesn't stop the editor from showing the errors during development.

**Comment by praveek** [comment]
Hi @vbasky 

You have to check if the brightscript language extension you use in your editor supports disabling linting for specific files.

These language specific extension work when the editor detects if the file is of specific language. If the extension does not support disabling linting for specific files, one workaround i can think of is to ignore language detection for adbmobile.brs file so that the brightscript extension ignores it. 
You can do it in vscode by having a project specific setting like 
```
{
"files.associations": {
  "**/adbmobile.brs": "ignore"
}
}
```

You should also be able to do something similar for atom.

Thanks,
Praveen

**Comment by vbasky** [comment]
@praveek Is there a plan to provide a wist compliant version of the adbmobile.brs file ?

**Comment by praveek** [comment]
No. We don't have it currently in our roadmap.
